### PR TITLE
Turn off parallelism when in test mode

### LINKED ISSUE #42: Different results from running the tests locally
Previously discussed in #40 

When I run the tests locally with `cargo test` on the `main` branch, I get very different results each time. Sometimes all the tests pass (which is somewhat rare), sometimes most of them fail.

Terminal screen capture:
https://asciinema.org/a/MGtehVJYHt76Pq1DTDQyRxv2J

Raw output captured by `script`:
[output.txt](https://github.com/imsnif/diskonaut/files/4813837/output.txt)

### PR DESCRIPTION
**Pull request by redzic**
Should fix #42

### CODE REVIEW

**Comment by redzic** [comment]
I'm not sure why but now only the first test (`tests::cases::ui::permission_denied_when_deleting`) is consistently not working, even with this change. I'll probably look into this later

**Comment by imsnif** [comment]
Hey @redzic, thanks for this. I changed the name a little because I felt it would be clearer this way, but otherwise great work :)

I'll merge this as soon as the tests pass. If you want another pair of eyes taking a look at why that tests is failing, do reach out.

**Comment by redzic** [comment]
The tests now consistently pass for me. I can't reproduce the behavior I was getting from before ¯\\\_(ツ)_/¯

**Comment by imsnif** [comment]
Quite odd indeed. Maybe we'll get a chance to debug it in the future :)

**Pull request merged**
