### PR TITLE
 Resolving #33 - Feature: show quit shortcut ('q') in the legend

### PR DESCRIPTION
**Pull request by olehs0**
Fixes https://github.com/imsnif/diskonaut/issues/33. Show ```<q> - quit``` at the bottom line.

### CODE REVIEW

**Comment by imsnif** [comment]
Hey @olehs0, can you do a `git rebase` from main? I think that should resolve the conflicts.

**Comment by olehs0** [comment]
Hey! Yes, sure, i just went to sleep after created a PR, and didn't fix the conflicts yet, sorry :) i'll fix it today

**Comment by imsnif** [comment]
Hey @olehs0 - it actually needs to be <arrows> :)

**Comment by olehs0** [comment]
@imsnif hi! what do you mean? is your comment related to me?

**Comment by imsnif** [comment]
In a previous PR, we changed the beginning of this line from `<hjkl> or <arrow keys>` to just `<arrows`. I think you changed it back by mistake.
Can you change it again to `<arrows>` and include your change with the quit? Once you do that, we can merge this. :)

**Comment by olehs0** [comment]
@imsnif ok, thank you for your response, got it - now should be fine

**Pull request merged**
