### PR TITLE
Resolving #32: implement a warning modal on deleting a file/folder while s…

### PR DESCRIPTION
**Pull request by mhdmhsni**
Hi @imsnif, this commit resolves https://github.com/imsnif/diskonaut/issues/32.
- added `WarningBox` to modals module.
- rendering logic is similar to other modals. nothing specific to mention.
- about the auto close functionality i added a `WarningTimeout` variant to your `Event` enum. this event waits for 5 seconds then resets the ui state using `Instruction::ResetUiMode`.

please let me know if anything needs to change.

### CODE REVIEW

**Comment by imsnif** [comment]
Hey @mhdmhsni, good job finding how to make this disappear with the Event mechanism. That's exactly the right way - sorry I wasn't around to make this easier. :)

I tested this branch and found a bug. While loading, if I try to delete a file, then dismiss the message by pressing ENTER, then try to delete the same file again quickly, everything gets stuck (might have to do this a few times fast).
I didn't investigate very deeply, but I suspect there is some sort of deadlock between the instruction channel and the park timeout.
While we can try and work around this, I feel the best way would be to give up on the timeout and wait for the user to dismiss this manually. I feel this is not bad UX and will save us some headaches. What do you think?

**Comment by mhdmhsni** [comment]
Hey @imsnif. Oops! I didn't see that bug coming. What comes to my mind about this situation is that maybe this ‘WarningTimeout‘ event should be cancellable. I mean if we close the warning modal manually, the timeout event keeps going (but it has to be cancelled automatically).
But i personally think giving more options to user to do a single thing, means adding more and more possibility of unwanted and unpredictable bugs and issues. So I'm agree with you.
so if any change needs to be done on this branch, please let me know. Thanks.

**Comment by imsnif** [comment]
Sounds good. So do you want to remove the cancellation timeout and make it only dismissable through the user pressing any key?

**Comment by mhdmhsni** [comment]
yes. i think regarding to the current situation this is the best approach. but maybe we can investigate about the auto close problem in another issue or something.

**Comment by imsnif** [comment]
Hey @mhdmhsni - changes look good. I'm going to take a closer look tomorrow.

**Comment by mhdmhsni** [comment]
Sorry, i forgot to change it myself after merging main branch into this one. thanks a lot.

**Pull request merged**
