### PR TITLE
Chore: bump deps

### PR DESCRIPTION
**Pull request by tim77**
tui to `0.8`
insta to `0.16.0`
cargo-insta to `0.16.0`

This related to packaging `diskonaut` for official Linux repos.

### CODE REVIEW

**Comment by imsnif** [comment]
I'm going to look into why the tests are failing in a short while (hopefully a little later today). I'm guessing this has to do with some hacks I've done in the test terminal backend. :)

**Comment by imsnif** [comment]
Hey @tim77 - I found the issue, but for some reason I'm not managing to push the changes to your branch so that this PR is updated.

In order to fix this, you'll need to rename all the files in src/tests/cases/snapshots, adding the prefix `diskonaut__tests__cases__ui__`
So that (for example):
`src/tests/cases/snapshots/ui__two_large_files_one_small_file.snap` -> `src/tests/cases/snapshots/diskonaut__tests__cases__ui__two_large_files_one_small_file.snap`

Makes sense?

**Comment by silwol** [comment]
Adding myself to the list of people interested in the deps update, I would like to package `diskonaut` for Debian main.
@tim77 is there any specific reason why you intend to update `tui` to `0.8` and not `0.9`?

**Comment by tim77** [comment]
> @tim77 is there any specific reason why you intend to update `tui` to `0.8` and not `0.9`?

Unfortunately yes. :) I guess we need to port `diskonaut` for newer version `tui` >= 0.8 because of some breaking changes. So this is more like temporal bump probably.

> for some reason I'm not managing to push the changes to your branch so that this PR is updated.

@imsnif this is weird. Will look to this very soon.

**Comment by silwol** [comment]
@tim77 see #30 - wasn't too hard luckily.

**Comment by imsnif** [comment]
Thank you very much, @tim77 ! I'm merging this.

@silwol and @tim77 - I'm not sure if you saw it or if this changes anything, but we added another small dependency in main on the filesize crate: https://github.com/imsnif/diskonaut/pull/28

**Comment by imsnif** [comment]
Hey @silwol - are you still interested in packaging diskonaut for Debian main? If so, is there anything I can do to help move this forward?

**Comment by silwol** [comment]
@imsnif I still am. For now, I don't see much you can do, we've still got some problems to solve regarding the Debian tooling before we can start continue to work on packaging, so it's more of a long-term goal. If I stumble over problems where you could help, I'll let you know.

**Pull request merged**
